FROM openjdk:17-slim as build

MAINTAINER ecom.com

COPY target/Service-Registry-0.0.1-SNAPSHOT.jar Service-Registry-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/Service-Registry-0.0.1-SNAPSHOT.jar"]